# Wazuh StorageClass

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: wazuh-storage
provisioner: kubernetes.io/aws-ebs
parameters:
  encrypted: 'true'
  type: gp2
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Retain  # Useful in case you delete the PersistentVolumeClaim
