apiVersion: v1
kind: Service
metadata:
  labels:
    app: thehive
  name: thehive-load
  namespace: thehive
spec:
  # type: NodePort
  # ports:
  #   - port: 9000
  #     nodePort: 30001
  # selector:
  #   app: thehive
  ports:
    - name: http
      port: 9000
      protocol: TCP
      targetPort: 9000
  selector:
    app: thehive
  type: LoadBalancer