apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: cortex
  name: "vault-cortex-job-io"
  labels:
    app: cortex
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi