apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: shuffle-opensearch
  name: shuffle-opensearch
spec:
  podManagementPolicy: OrderedReady
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: shuffle-opensearch
  serviceName: shuffle-opensearch
  template:
    metadata:
      labels:
        app: shuffle-opensearch
    spec:
      containers:
      - env:
        - name: bootstrap.memory_lock
          value: 'false'
        - name: OPENSEARCH_JAVA_OPTS
          value: '-Xms1g -Xmx1g'
        - name: cluster.routing.allocation.disk.threshold_enabled
          value: 'false'
        - name: cluster.name
          value: shuffle-cluster
        - name: node.name
          value: shuffle-opensearch          
        # - name: discovery.seed_hosts
        #   value: shuffle-opensearch
        # - name: cluster.initial_master_nodes
        #   value: shuffle-opensearch
        - name: discovery.type
          value: single-node
        # - name: es.enforce.bootstrap.checks
        #   value: 'false'
        - name: DISABLE_SECURITY_PLUGIN
          value: 'true'
        image: opensearchproject/opensearch:2.5.0
        imagePullPolicy: IfNotPresent
        name: shuffle-opensearch
        ports:
        - containerPort: 9200
          name: transport
          protocol: TCP
        volumeMounts:
        - name: storage
          mountPath: /etc/shuffle
      hostname: shuffle-opensearch
      volumes:
        - name: storage
          emptyDir: {}
      restartPolicy: Always
      terminationGracePeriodSeconds: 0
  volumeClaimTemplates: []