apiVersion: v1
kind: Service
metadata:
  name: release-name-cortex
  labels:
    app: cortex
spec:
  type: ClusterIP
  ports:
    - port: 9001
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: cortex
    app.kubernetes.io/instance: release-name