apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: shuffle-frontend
  name: shuffle-frontend
spec:
  podManagementPolicy: OrderedReady
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: shuffle-frontend
  serviceName: shuffle-frontend
  template:
    metadata:
      labels:
        app: shuffle-frontend
    spec:
      containers:
      - env:
        - name: BACKEND_HOSTNAME
          value: shuffle-backend
        image: ghcr.io/frikky/shuffle-frontend:latest
        imagePullPolicy: IfNotPresent
        name: shuffle-frontend
        ports:
        - containerPort: 80
          name: port80
          protocol: TCP
        - containerPort: 443
          name: port443
          protocol: TCP
      restartPolicy: Always