apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: service123-job-runner
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: job-runner
subjects:
  - kind: ServiceAccount
    namespace: cortex
    name: service123