apiVersion: v1
kind: Service
metadata:
  labels:
    app: shuffle-backend
  name: shuffle-backend
spec:
  ports:
  - name: nameme-01
    port: 5001
    protocol: TCP
    targetPort: 5001
  selector:
    app: shuffle-backend
  type: NodePort