apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app: cortex

resources:
  - storage/cortex-pv.yaml
  - storage/cortex-pvc.yaml

  - conf/cortex-cm.yaml

  - secrets/cortex-auth.yaml
  - secrets/cortex-sc.yaml

  - manage/cortex-rb.yaml
  - manage/cortex-sa.yaml
  - manage/cortex-rl.yaml

  - service/cortex-svs.yaml
  - service/loadbalancer.yaml

  - cortex-dp.yaml
  
