apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: minio
  namespace: thehive
  labels:
    app: minio
spec:
  serviceName: minio
  replicas: 1
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      terminationGracePeriodSeconds: 1800
      containers:
        - name: minio
          image: quay.io/minio/minio
          command: ["minio", "server", "/data", "--console-address", ":9001"]
          env:
            - name: MINIO_ROOT_USER
              value: minioadmin
            - name: MINIO_ROOT_PASSWORD
              value: minioadmin
          ports:
            - containerPort: 9000
              name: http
          resources:
            limits:
              cpu: "500m"
              memory: 512Mi
            requests:
              cpu: "500m"
              memory: 256Mi
          volumeMounts:
            - name: s3-data
              mountPath: /data
      volumes:
        - name: s3-data
          emptyDir: {}