apiVersion: v1
kind: Service
metadata:
  name: cortex-master
spec:
  clusterIP: None
  ports:
    - name: transport
      port: 9001
      protocol: TCP
      targetPort: 9001
  selector:
    app: cortex
  publishNotReadyAddresses: true
  sessionAffinity: None
  type: ClusterIP