apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cortex
spec:
  podManagementPolicy: Parallel
  replicas: 1
  selector:
    matchLabels:
      app: cortex
  serviceName: cortex
  template:
    metadata:
      labels:
         app: cortex
    spec:
      containers:
        - name: cortex
          image: thehiveproject/cortex
          imagePullPolicy: IfNotPresent
          env:
            - name: job_directory
              value: '/tmp/cortex-jobs'
          # livenessProbe:
          #   exec:
          #     command:
          #       - cat
          #       - /tmp/healthy
          #   initialDelaySeconds: 5
          #   periodSeconds: 5
          # readinessProbe:
          #   failureThreshold: 3
          #   initialDelaySeconds: 15
          #   periodSeconds: 10
          #   successThreshold: 1
          #   tcpSocket:
          #     port: 9300
          #   timeoutSeconds: 5
          resources:
            limits:
              # cpu: '1'
              memory: 1Gi
            requests:
              cpu: 100m
              memory: 500Mi
          securityContext:
            privileged: true
          ports:
            - containerPort: 9001
              name: transport
              protocol: TCP
          volumeMounts:

            #miss configuration 
            # - name: docker.sock
            #   subPath: docker.sock
            #   mountPath: /var/run/docker.sock
            
            - name: storage
              subPath: cortex-jobs
              mountPath: /tmp/cortex-jobs
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 20
      volumes:
        - name: storage
          emptyDir: {}
  updateStrategy:
    type: OnDelete
  volumeClaimTemplates: []

