apiVersion: v1
kind: ConfigMap
metadata:
  namespace: cortex
  name: "vault-cortex-etc-c-tmpl"
data:
  
  # Avoid getting configuration, with secrets, catted out to
  # logs. That is a dev thing to do, not a prod thing to do.
  application.conf.tmpl: |
    include file("/etc/cortex/main.conf")
  main.conf.tmpl: |
    play.http.secret.key="@@PLAY_HTTP_SECRET_KEY@@"
    search {
        uri = "http://elasticsearch-client.thehive:9200"
    }
    job {
        directory = /tmp/cortex-jobs
        kubernetes {
            persistentVolumeClaimName = "vault-cortex-job-io"
        }
    }
    analyzer.urls = [
      "https://download.thehive-project.org/analyzers.json"
    ]
    responder.urls = [
      "https://download.thehive-project.org/responders.json"
    ]
    
  logback.xml.tmpl: |
    <?xml version="1.0" encoding="UTF-8"?>
    <configuration debug="false">
        <!-- stdout only, no colors -->
        <appender name="STDOUT" class="ch.qos.logback.core.ConsoleAppender">
            <encoder>
                <pattern>%date [%level] from %logger in %thread - %message%n%xException</pattern>
            </encoder>
        </appender>
        <appender name="ASYNCSTDOUT" class="ch.qos.logback.classic.AsyncAppender">
            <appender-ref ref="STDOUT"/>
        </appender>
        <logger name="play" level="INFO"/>
        <logger name="application" level="INFO"/>
        <logger name="com.gargoylesoftware.htmlunit.javascript" level="OFF"/>
        <root level="INFO">
            <appender-ref ref="ASYNCSTDOUT"/>
        </root>
    </configuration>