apiVersion: v1
kind: Service
metadata:
  name: shuffle-opensearch
spec:
  clusterIP: None
  ports:
    - name: transport
      port: 9200
      protocol: TCP
      targetPort: 9200
  selector:
    app: shuffle-opensearch
  type: ClusterIP