apiVersion: v1
kind: Service
metadata:
  labels:
    role: master
  name: elasticsearch-master
spec:
  clusterIP: None
  ports:
    - name: transport
      port: 9300
      protocol: TCP
      targetPort: 9300
  selector:
    app: elasticsearch
    role: master
  publishNotReadyAddresses: true
  sessionAffinity: None
  type: ClusterIP