apiVersion: v1
kind: Service
metadata:
  labels:
    app: thehive-elasticsearch
  name: thehive-elasticsearch
  namespace: thehive
spec:
  ports:
    - port: 9200
  selector:
    app: thehive-elasticsearch
