apiVersion: v1
kind: Service
metadata:
  name: kibana-service
spec:
  clusterIP: None
  ports:
    - name: http
      port: 5601
      protocol: TCP
      targetPort: 5601
  selector:
    app: kibana
  publishNotReadyAddresses: true
  sessionAffinity: None
  type: ClusterIP